//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.1433
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontel.Relkon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FormLocation {
            get {
                return ((global::System.Drawing.Point)(this["FormLocation"]));
            }
            set {
                this["FormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("968, 628")]
        public global::System.Drawing.Size FormSize {
            get {
                return ((global::System.Drawing.Size)(this["FormSize"]));
            }
            set {
                this["FormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FormWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FormWindowState"]));
            }
            set {
                this["FormWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SolutionExplorerIsOpen {
            get {
                return ((bool)(this["SolutionExplorerIsOpen"]));
            }
            set {
                this["SolutionExplorerIsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SolutionExplorerCollapsed {
            get {
                return ((bool)(this["SolutionExplorerCollapsed"]));
            }
            set {
                this["SolutionExplorerCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250, 400")]
        public global::System.Drawing.Size SolutionExplorerFloatingSize {
            get {
                return ((global::System.Drawing.Size)(this["SolutionExplorerFloatingSize"]));
            }
            set {
                this["SolutionExplorerFloatingSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int SolutionExplorerPopupSize {
            get {
                return ((int)(this["SolutionExplorerPopupSize"]));
            }
            set {
                this["SolutionExplorerPopupSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250, 400")]
        public global::System.Drawing.Size SolutionExplorerStaticSize {
            get {
                return ((global::System.Drawing.Size)(this["SolutionExplorerStaticSize"]));
            }
            set {
                this["SolutionExplorerStaticSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Top")]
        public string MainToolStripPanel {
            get {
                return ((string)(this["MainToolStripPanel"]));
            }
            set {
                this["MainToolStripPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 24")]
        public global::System.Drawing.Point MainToolStriplLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainToolStriplLocation"]));
            }
            set {
                this["MainToolStriplLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Top")]
        public string PultToolStripPanel {
            get {
                return ((string)(this["PultToolStripPanel"]));
            }
            set {
                this["PultToolStripPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 49")]
        public global::System.Drawing.Point PultToolStripLocation {
            get {
                return ((global::System.Drawing.Point)(this["PultToolStripLocation"]));
            }
            set {
                this["PultToolStripLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelectedProcessorIndex {
            get {
                return ((int)(this["SelectedProcessorIndex"]));
            }
            set {
                this["SelectedProcessorIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int ErrorsListDescriptionColumnWidth {
            get {
                return ((int)(this["ErrorsListDescriptionColumnWidth"]));
            }
            set {
                this["ErrorsListDescriptionColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ErrorsListFileColumnWidth {
            get {
                return ((int)(this["ErrorsListFileColumnWidth"]));
            }
            set {
                this["ErrorsListFileColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ErrorsListLastModifySizeColumnIndex {
            get {
                return ((int)(this["ErrorsListLastModifySizeColumnIndex"]));
            }
            set {
                this["ErrorsListLastModifySizeColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int ErrorsListLineColumnWidth {
            get {
                return ((int)(this["ErrorsListLineColumnWidth"]));
            }
            set {
                this["ErrorsListLineColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastOpenedSolutionDirectory {
            get {
                return ((string)(this["LastOpenedSolutionDirectory"]));
            }
            set {
                this["LastOpenedSolutionDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 9.75pt")]
        public global::System.Drawing.Font EditorFont {
            get {
                return ((global::System.Drawing.Font)(this["EditorFont"]));
            }
            set {
                this["EditorFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainToolStripVisible {
            get {
                return ((bool)(this["MainToolStripVisible"]));
            }
            set {
                this["MainToolStripVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PultToolStripVisible {
            get {
                return ((bool)(this["PultToolStripVisible"]));
            }
            set {
                this["PultToolStripVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 9.75pt")]
        public global::System.Drawing.Font DefaultEditorFont {
            get {
                return ((global::System.Drawing.Font)(this["DefaultEditorFont"]));
            }
            set {
                this["DefaultEditorFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Top")]
        public string DispatcheringToolStripPanel {
            get {
                return ((string)(this["DispatcheringToolStripPanel"]));
            }
            set {
                this["DispatcheringToolStripPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 99")]
        public global::System.Drawing.Point DispatcheringToolStripLocation {
            get {
                return ((global::System.Drawing.Point)(this["DispatcheringToolStripLocation"]));
            }
            set {
                this["DispatcheringToolStripLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 124")]
        public global::System.Drawing.Point ArchiveToolStripLocation {
            get {
                return ((global::System.Drawing.Point)(this["ArchiveToolStripLocation"]));
            }
            set {
                this["ArchiveToolStripLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string DeBugger_Settings_ComPort {
            get {
                return ((string)(this["DeBugger_Settings_ComPort"]));
            }
            set {
                this["DeBugger_Settings_ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19200")]
        public int DeBugger_Settings_BaudRate {
            get {
                return ((int)(this["DeBugger_Settings_BaudRate"]));
            }
            set {
                this["DeBugger_Settings_BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MB90F347")]
        public string DeBugger_SettingsProcessesorType {
            get {
                return ((string)(this["DeBugger_SettingsProcessesorType"]));
            }
            set {
                this["DeBugger_SettingsProcessesorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RC51ASCII")]
        public string DeBugger_Settings_Protocol {
            get {
                return ((string)(this["DeBugger_Settings_Protocol"]));
            }
            set {
                this["DeBugger_Settings_Protocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DeBugger_Settings_NumberLink {
            get {
                return ((int)(this["DeBugger_Settings_NumberLink"]));
            }
            set {
                this["DeBugger_Settings_NumberLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebuggerParametersListCollapsed {
            get {
                return ((bool)(this["DebuggerParametersListCollapsed"]));
            }
            set {
                this["DebuggerParametersListCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string ModulesCOMPort {
            get {
                return ((string)(this["ModulesCOMPort"]));
            }
            set {
                this["ModulesCOMPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("376")]
        public int ModulesFormHeight {
            get {
                return ((int)(this["ModulesFormHeight"]));
            }
            set {
                this["ModulesFormHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int ModulesFormSplitterDistance {
            get {
                return ((int)(this["ModulesFormSplitterDistance"]));
            }
            set {
                this["ModulesFormSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchString {
            get {
                return ((string)(this["SearchString"]));
            }
            set {
                this["SearchString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReplaceString {
            get {
                return ((string)(this["ReplaceString"]));
            }
            set {
                this["ReplaceString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Top")]
        public string DebuggerToolStripPanel {
            get {
                return ((string)(this["DebuggerToolStripPanel"]));
            }
            set {
                this["DebuggerToolStripPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 74")]
        public global::System.Drawing.Point DebuggerToolStripLocation {
            get {
                return ((global::System.Drawing.Point)(this["DebuggerToolStripLocation"]));
            }
            set {
                this["DebuggerToolStripLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebuggerToolStripVisible {
            get {
                return ((bool)(this["DebuggerToolStripVisible"]));
            }
            set {
                this["DebuggerToolStripVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebuggerHex {
            get {
                return ((bool)(this["DebuggerHex"]));
            }
            set {
                this["DebuggerHex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("251, 661")]
        public global::System.Drawing.Size DebuggerParametersListSize {
            get {
                return ((global::System.Drawing.Size)(this["DebuggerParametersListSize"]));
            }
            set {
                this["DebuggerParametersListSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("251")]
        public int DebuggerParametersListPopupSize {
            get {
                return ((int)(this["DebuggerParametersListPopupSize"]));
            }
            set {
                this["DebuggerParametersListPopupSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("251, 661")]
        public global::System.Drawing.Size DebuggerParametersListStaticSize {
            get {
                return ((global::System.Drawing.Size)(this["DebuggerParametersListStaticSize"]));
            }
            set {
                this["DebuggerParametersListStaticSize"] = value;
            }
        }
    }
}
