//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.1433
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontel.Components.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kontel.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ArchiveDbTemplate {
            get {
                object obj = ResourceManager.GetObject("ArchiveDbTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Collapsed {
            get {
                object obj = ResourceManager.GetObject("Collapsed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ControllerProgramTemplate {
            get {
                object obj = ResourceManager.GetObject("ControllerProgramTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Expanded {
            get {
                object obj = ResourceManager.GetObject("Expanded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pointer {
            get {
                object obj = ResourceManager.GetObject("Pointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PointerBlack {
            get {
                object obj = ResourceManager.GetObject("PointerBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Appearance.
        /// </summary>
        internal static string SRAppearanceCategory {
            get {
                return ResourceManager.GetString("SRAppearanceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Layout.
        /// </summary>
        internal static string SRLayoutCategory {
            get {
                return ResourceManager.GetString("SRLayoutCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the AllowNestedTabs property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxAllowNestedTabsChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxAllowNestedTabsChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indicates whether to allow nesting of tabs..
        /// </summary>
        internal static string SRToolboxAllowNestedTabsDescr {
            get {
                return ResourceManager.GetString("SRToolboxAllowNestedTabsDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the AllowToolboxItems property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxAllowToolboxItemsChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxAllowToolboxItemsChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indicates whether to allow items that do not belong to any category..
        /// </summary>
        internal static string SRToolboxAllowToolboxItemsDescr {
            get {
                return ResourceManager.GetString("SRToolboxAllowToolboxItemsDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toolbox Appearance.
        /// </summary>
        internal static string SRToolboxAppearanceCategory {
            get {
                return ResourceManager.GetString("SRToolboxAppearanceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the AutoScroll property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxAutoScrollChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxAutoScrollChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indicates whether scrollbar automatically appear when the Toolbox content height is larger than its visible area..
        /// </summary>
        internal static string SRToolboxAutoScrollDescr {
            get {
                return ResourceManager.GetString("SRToolboxAutoScrollDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the GradientBackColorEnd property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxBackColorGradientEndChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxBackColorGradientEndChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The gradient end color used to draw background of the Toolbox..
        /// </summary>
        internal static string SRToolboxBackColorGradientEndDescr {
            get {
                return ResourceManager.GetString("SRToolboxBackColorGradientEndDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the GradientBackColorStart property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxBackColorGradientStartChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxBackColorGradientStartChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The gradient start color used to draw background of the Toolbox..
        /// </summary>
        internal static string SRToolboxBackColorGradientStartDescr {
            get {
                return ResourceManager.GetString("SRToolboxBackColorGradientStartDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indicates the border style for the control..
        /// </summary>
        internal static string SRToolboxBorderStyleDescr {
            get {
                return ResourceManager.GetString("SRToolboxBorderStyleDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The categories in Toolbox..
        /// </summary>
        internal static string SRToolboxCategoriesDescr {
            get {
                return ResourceManager.GetString("SRToolboxCategoriesDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toolbox.
        /// </summary>
        internal static string SRToolboxCategory {
            get {
                return ResourceManager.GetString("SRToolboxCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indicates whether to create &apos;General&apos; category tab..
        /// </summary>
        internal static string SRToolboxCreateGeneralDescr {
            get {
                return ResourceManager.GetString("SRToolboxCreateGeneralDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Represents a control, which displays a collection of items separated by categories..
        /// </summary>
        internal static string SRToolboxDescription {
            get {
                return ResourceManager.GetString("SRToolboxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the DrawTabLevel property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxDrawTabLevelChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxDrawTabLevelChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indicates whether to draw tab level mark..
        /// </summary>
        internal static string SRToolboxDrawTabLevelDescr {
            get {
                return ResourceManager.GetString("SRToolboxDrawTabLevelDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the ItemHeight property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxItemHeightChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxItemHeightChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The height of toolbox items in pixels..
        /// </summary>
        internal static string SRToolboxItemHeightDescr {
            get {
                return ResourceManager.GetString("SRToolboxItemHeightDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the ItemHoverColor property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxItemHoverColorChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxItemHoverColorChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The color used to fill background of hovered item..
        /// </summary>
        internal static string SRToolboxItemHoverColorDescr {
            get {
                return ResourceManager.GetString("SRToolboxItemHoverColorDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Displays a shortcut menu when the user right-clicks on any item..
        /// </summary>
        internal static string SRToolboxItemMenuDescr {
            get {
                return ResourceManager.GetString("SRToolboxItemMenuDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The collection of items in the Toolbox..
        /// </summary>
        internal static string SRToolboxItemsDescr {
            get {
                return ResourceManager.GetString("SRToolboxItemsDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the ItemSelectBorderColor property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxItemSelectBorderColorChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxItemSelectBorderColorChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The color used to draw a border around selected item..
        /// </summary>
        internal static string SRToolboxItemSelectBorderColorDescr {
            get {
                return ResourceManager.GetString("SRToolboxItemSelectBorderColorDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the ItemSelectColor property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxItemSelectColorChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxItemSelectColorChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The color used to fill background of selected item..
        /// </summary>
        internal static string SRToolboxItemSelectColorDescr {
            get {
                return ResourceManager.GetString("SRToolboxItemSelectColorDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the ItemSelectHoverColor property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxItemSelHoverColorChanged {
            get {
                return ResourceManager.GetString("SRToolboxItemSelHoverColorChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The color used to fill background of hovered and selected item..
        /// </summary>
        internal static string SRToolboxItemSelHoverColorDescr {
            get {
                return ResourceManager.GetString("SRToolboxItemSelHoverColorDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Occurs when the Toolbox control is scrolled by user or programmatically..
        /// </summary>
        internal static string SRToolboxScrollDescr {
            get {
                return ResourceManager.GetString("SRToolboxScrollDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when item is selected on Toolbox..
        /// </summary>
        internal static string SRToolboxSelectItemDescr {
            get {
                return ResourceManager.GetString("SRToolboxSelectItemDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the ShowAll property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxShowAllChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxShowAllChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indicates whether to show all items, even if they were disabled and hidden..
        /// </summary>
        internal static string SRToolboxShowAllDescr {
            get {
                return ResourceManager.GetString("SRToolboxShowAllDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the ShowIcons property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxShowIconsChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxShowIconsChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indicates whether icons of items are drawn..
        /// </summary>
        internal static string SRToolboxShowIconsDescr {
            get {
                return ResourceManager.GetString("SRToolboxShowIconsDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the ShowPointer property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxShowPointerChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxShowPointerChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indicates whether to show pointer item..
        /// </summary>
        internal static string SRToolboxShowPointerDescr {
            get {
                return ResourceManager.GetString("SRToolboxShowPointerDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the TabColorStyle property is changed on the Toolbox..
        /// </summary>
        internal static string SRToolboxTabColorStyleChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxTabColorStyleChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indicates style of drawing tab background..
        /// </summary>
        internal static string SRToolboxTabColorStyleDescr {
            get {
                return ResourceManager.GetString("SRToolboxTabColorStyleDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the TabFont property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxTabFontChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxTabFontChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Font used to display tab headers text..
        /// </summary>
        internal static string SRToolboxTabFontDescr {
            get {
                return ResourceManager.GetString("SRToolboxTabFontDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the TabHeight property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxTabHeightChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxTabHeightChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The height of tab captions in pixels..
        /// </summary>
        internal static string SRToolboxTabHeightDescr {
            get {
                return ResourceManager.GetString("SRToolboxTabHeightDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Displays a shortcut menu when the user right-clicks on any tab..
        /// </summary>
        internal static string SRToolboxTabMenuDescr {
            get {
                return ResourceManager.GetString("SRToolboxTabMenuDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the TabSelectBorderColor property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxTabSelectBorderColorChangedDescr {
            get {
                return ResourceManager.GetString("SRToolboxTabSelectBorderColorChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The color used to draw a border around selected tab..
        /// </summary>
        internal static string SRToolboxTabSelectBorderColorDescr {
            get {
                return ResourceManager.GetString("SRToolboxTabSelectBorderColorDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event raised when the value of the TabSelectColor property is changed on Toolbox..
        /// </summary>
        internal static string SRToolboxTabSelectColorChanged {
            get {
                return ResourceManager.GetString("SRToolboxTabSelectColorChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The color used to fill background of selected tab..
        /// </summary>
        internal static string SRToolboxTabSelectColorDescr {
            get {
                return ResourceManager.GetString("SRToolboxTabSelectColorDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toolbox.
        /// </summary>
        internal static string SRToolboxToolboxCategory {
            get {
                return ResourceManager.GetString("SRToolboxToolboxCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item has to be added to one of categories.
        /// </summary>
        internal static string ToolboxDeleteNonTabbedItem {
            get {
                return ResourceManager.GetString("ToolboxDeleteNonTabbedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Caption cannot be empty..
        /// </summary>
        internal static string ToolboxEmptyTextMessage {
            get {
                return ResourceManager.GetString("ToolboxEmptyTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на That item belongs to another collection.
        /// </summary>
        internal static string ToolboxExceptionItemHasOtherOwner {
            get {
                return ResourceManager.GetString("ToolboxExceptionItemHasOtherOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на That item is already in the collection.
        /// </summary>
        internal static string ToolboxExceptionItemIsInCollection {
            get {
                return ResourceManager.GetString("ToolboxExceptionItemIsInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not add a tab to itself.
        /// </summary>
        internal static string ToolboxExceptionTabAddSelf {
            get {
                return ResourceManager.GetString("ToolboxExceptionTabAddSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Tab.
        /// </summary>
        internal static string ToolboxMenuAddTab {
            get {
                return ResourceManager.GetString("ToolboxMenuAddTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        internal static string ToolboxMenuCopy {
            get {
                return ResourceManager.GetString("ToolboxMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cut.
        /// </summary>
        internal static string ToolboxMenuCut {
            get {
                return ResourceManager.GetString("ToolboxMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string ToolboxMenuDelete {
            get {
                return ResourceManager.GetString("ToolboxMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move Down.
        /// </summary>
        internal static string ToolboxMenuMoveDown {
            get {
                return ResourceManager.GetString("ToolboxMenuMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move Up.
        /// </summary>
        internal static string ToolboxMenuMoveUp {
            get {
                return ResourceManager.GetString("ToolboxMenuMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste.
        /// </summary>
        internal static string ToolboxMenuPaste {
            get {
                return ResourceManager.GetString("ToolboxMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename Item.
        /// </summary>
        internal static string ToolboxMenuRenameItem {
            get {
                return ResourceManager.GetString("ToolboxMenuRenameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename Tab.
        /// </summary>
        internal static string ToolboxMenuRenameTab {
            get {
                return ResourceManager.GetString("ToolboxMenuRenameTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset Toolbox.
        /// </summary>
        internal static string ToolboxMenuResetToolbox {
            get {
                return ResourceManager.GetString("ToolboxMenuResetToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show All.
        /// </summary>
        internal static string ToolboxMenuShowAll {
            get {
                return ResourceManager.GetString("ToolboxMenuShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort Items Alphabetically.
        /// </summary>
        internal static string ToolboxMenuSortAlphabetically {
            get {
                return ResourceManager.GetString("ToolboxMenuSortAlphabetically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Tab.
        /// </summary>
        internal static string ToolboxMenuTabDelete {
            get {
                return ResourceManager.GetString("ToolboxMenuTabDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pointer.
        /// </summary>
        internal static string ToolboxPointerItem {
            get {
                return ResourceManager.GetString("ToolboxPointerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot rename &apos;Nothing&apos;!.
        /// </summary>
        internal static string ToolboxRenamerNothingToRename {
            get {
                return ResourceManager.GetString("ToolboxRenamerNothingToRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only Tab or Item objects could be renamed!.
        /// </summary>
        internal static string ToolboxRenamerNotItemNorTab {
            get {
                return ResourceManager.GetString("ToolboxRenamerNotItemNorTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot select disabled item!.
        /// </summary>
        internal static string ToolboxSelectDisabledItem {
            get {
                return ResourceManager.GetString("ToolboxSelectDisabledItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot select item or tab which is not visible!.
        /// </summary>
        internal static string ToolboxSelectNonVisibleTool {
            get {
                return ResourceManager.GetString("ToolboxSelectNonVisibleTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category.
        /// </summary>
        internal static string ToolboxTabDefaultName {
            get {
                return ResourceManager.GetString("ToolboxTabDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        internal static string ToolboxTabGeneral {
            get {
                return ResourceManager.GetString("ToolboxTabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа пуста. Переместите блок на этот текст для того,что бы добавить его..
        /// </summary>
        internal static string ToolboxTabNoItemsText {
            get {
                return ResourceManager.GetString("ToolboxTabNoItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste Item.
        /// </summary>
        internal static string ToolboxTabPasteItem {
            get {
                return ResourceManager.GetString("ToolboxTabPasteItem", resourceCulture);
            }
        }
    }
}
