PATH ..\..\Distr\arm-gcc\bin;

del ..\..\Distr\firmware\STM32F107\obj\*.o /Q
del ..\..\Distr\firmware\STM32F107\inc\*.h /Q

copy .\ETH_DRIVER\*.h ..\..\Distr\firmware\STM32F107\inc
copy .\KONLITE\inc\*.h ..\..\Distr\firmware\STM32F107\inc
copy .\KONLITE\src\*.h ..\..\Distr\firmware\STM32F107\inc
copy .\FreeRTOS\include\*.h ..\..\Distr\firmware\STM32F107\inc
copy .\Libraries\STM32F10x_StdPeriph_Driver\inc\*.h ..\..\Distr\firmware\STM32F107\inc
copy .\Libraries\CMSIS\Core\CM3\*.h ..\..\Distr\firmware\STM32F107\inc
copy .\Relkon\inc\*.h ..\..\Distr\firmware\STM32F107\inc
copy .\Relkon_PORT\inc\*.h ..\..\Distr\firmware\STM32F107\inc
copy .\FATFS\inc\*.h ..\..\Distr\firmware\STM32F107\inc
copy .\FATFS\inc\*.h ..\..\Distr\firmware\STM32F107\inc
copy .\CC3000_DRIVER\inc*.h ..\..\Distr\firmware\STM32F107\inc

copy .\stm32_flash.ld ..\..\Distr\firmware\STM32F107

arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_bkp.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_bkp.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_rcc.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_rcc.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/hdac.o .\Relkon_PORT\src\hdac.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/hain.o .\Relkon_PORT\src\hain.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/master.o .\Relkon\src\master.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/wifi.o .\Relkon\src\wifi.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/system_stm32f10x.o .\Libraries\CMSIS\Core\CM3\system_stm32f10x.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/http_data.o .\Relkon\src\http_data.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/canal.o .\Relkon\src\canal.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_spi.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_spi.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/fram.o .\Relkon\src\fram.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/nvmem.o .\CC3000_DRIVER\src\nvmem.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/sdcard.o .\Relkon\src\sdcard.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/cc3000_common.o .\CC3000_DRIVER\src\cc3000_common.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/hcanal.o .\Relkon_PORT\src\hcanal.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/htime.o .\Relkon_PORT\src\htime.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_dbgmcu.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_dbgmcu.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/fc_u.o .\Relkon\src\fc_u.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_gpio.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_gpio.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/k_mac.o .\KONLITE\src\k_mac.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_wwdg.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_wwdg.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/wlan.o .\CC3000_DRIVER\src\wlan.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_pwr.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_pwr.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/list.o .\FreeRTOS\list.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/k_arp.o .\KONLITE\src\k_arp.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/heap_2.o .\FreeRTOS\heap_2.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_dma.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_dma.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_tim.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_tim.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/modbus.o .\Relkon\src\protocol\modbus.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_flash.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_flash.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_exti.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_exti.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/k_udp.o .\KONLITE\src\k_udp.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/netapp.o .\CC3000_DRIVER\src\netapp.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/k_http.o .\KONLITE\src\k_http.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/k_icmp.o .\KONLITE\src\k_icmp.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/exchange.o .\Relkon\src\exchange.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/fat_cache.o .\FATFS\src\fat_cache.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/rk.o .\Relkon\src\protocol\rk.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/hmain.o .\Relkon_PORT\src\hmain.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/modbustcp.o .\Relkon\src\protocol\modbustcp.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/heth.o .\Relkon_PORT\src\heth.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_rtc.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_rtc.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/croutine.o .\FreeRTOS\croutine.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_adc.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_adc.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_dac.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_dac.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_sdio.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_sdio.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_fsmc.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_fsmc.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -Wa,--warn -x assembler-with-cpp -o ../../Distr/firmware/STM32F107/obj/startup_stm32f10x_cl.o .\Libraries\CMSIS\Core\CM3\startup\gcc\startup_stm32f10x_cl.s
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/hfram.o .\Relkon_PORT\src\hfram.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/hci.o .\CC3000_DRIVER\src\hci.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/fat_filelib.o .\FATFS\src\fat_filelib.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/port.o .\FreeRTOS\port.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/main.o .\Relkon\src\main.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_crc.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_crc.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/hinout.o .\Relkon_PORT\src\hinout.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/string_func.o .\Relkon\src\string_func.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/fat_misc.o .\FATFS\src\fat_misc.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/fat_write.o .\FATFS\src\fat_write.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_i2c.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_i2c.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/mmb.o .\Relkon\src\mmb.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/fat_string.o .\FATFS\src\fat_string.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/core_cm3.o .\Libraries\CMSIS\Core\CM3\core_cm3.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/inout.o .\Relkon\src\inout.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/print.o .\Relkon\src\print.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/queue.o .\FreeRTOS\queue.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/tasks.o .\FreeRTOS\tasks.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32_eth.o .\ETH_DRIVER\stm32_eth.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/fat_access.o .\FATFS\src\fat_access.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/k_main.o .\KONLITE\src\k_main.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/eth_task.o .\Relkon\src\eth_task.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_can.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_can.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_iwdg.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_iwdg.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/k_tcp.o .\KONLITE\src\k_tcp.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/evnt_handler.o .\CC3000_DRIVER\src\evnt_handler.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/hsd.o .\Relkon_PORT\src\hsd.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/socket.o .\CC3000_DRIVER\src\socket.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/k_ip.o .\KONLITE\src\k_ip.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/fat_table.o .\FATFS\src\fat_table.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/stm32f10x_usart.o .\Libraries\STM32F10x_StdPeriph_Driver\src\stm32f10x_usart.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/lcd.o .\Relkon\src\lcd.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/hlcd.o .\Relkon_PORT\src\hlcd.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/misc.o .\Libraries\STM32F10x_StdPeriph_Driver\src\misc.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/modem.o .\Relkon\src\modem.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/fat_format.o .\FATFS\src\fat_format.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/hwifi.o .\Relkon_PORT\src\hwifi.c
arm-none-eabi-gcc -c -mthumb -mcpu=cortex-m3 -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -D__CCS__ -I ./ETH_DRIVER -I ./KONLITE/inc -I ./KONLITE/src -I ./FreeRTOS/include -I ./Libraries/STM32F10x_StdPeriph_Driver/inc -I ./Libraries/CMSIS/Core/CM3 -I ./Relkon/inc -I ./Relkon_PORT/inc -I ./FATFS/inc -I ./CC3000_DRIVER/inc -Os -ffunction-sections -fdata-sections -Wall -Os -mlittle-endian -fsigned-char -o ../../Distr/firmware/STM32F107/obj/crc.o .\Relkon\src\crc.c

